version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    command:
      ['./bin/wait-for-it.sh', 'db:5432', '--', './bin/start-server.sh']
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
    volumes:
      - .:/www/
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sportsbook_user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: sportsbook_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data:
