version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8  # ou qualquer outra versão que você esteja usando

    working_directory: ~/repo

    steps:
      - checkout  # Verifique o código da branch no diretório de trabalho
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

