version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
        environment:
          DATABASE_URL: postgres://test:test@localhost:5432/test_db
      - image: circleci/postgres:10.0
        environment:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db
    working_directory: ~/repo

    steps:
      - checkout  
      - run:
          name: Wait for PostgreSQL to start
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

