version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8  # or any other version you're using

    working_directory: ~/repo

    steps:
      - checkout  # Check out the code from the branch into the working directory
      - run:
          name: Install dependencies
          command: pip install pytest
      - run:
          name: Run tests
          command: pytest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

